### ISSUE TITLE
LGA grouping strategy

### ISSUE THREAD

**Issue by Tcode8** [LiyingCV/Long-Range-Grouping-Transformer#16]
Thank you for your excellent work. While studying your work, I was not very familiar with the implementation of LGA grouping code. Could you please explain to me what these dimensional changes represent and how they reflect the grouping of different blocks
‘’‘
q_cls, k_cls, v_cls = map(lambda t: rearrange(t, '(b v) h (t1 s1 t2 s2) d -> b (s1 s2) h (t1 t2 v) d',
                                                          b=b_s, v=view_num, t1=token_num, s1=self.group_num, t2=token_num,
                                                          s2=self.group_num), (q, k, v))
’‘’
looking for your reply！

**Comment by LiyingCV** [comment]
Hi, the implementations mean we sample the tokens that are **not adjacent to** each other in terms of the same view features, and through the map function, we can obtain the grouped set as q_cls, k_cls, v_cls.

**Comment by Tcode8** [comment]
Thank you for your reply. So how does this reflect the allocation of tokens with the same color scheme to the same group mentioned in the paper？ I feel like the code is randomly grouped

**Comment by Tcode8** [comment]
> **你好，具体实现意思是，我们对相同视角特征不相邻的**token进行采样，通过map函数得到分组后的集合q_cls，k_cls，v_cls。

Thank you for your reply. So how does this reflect the allocation of tokens with the same color scheme to the same group mentioned in the paper？ I feel like the code is randomly grouped

**Comment by LiyingCV** [comment]
> > **你好，具体实现意思是，我们对相同视角特征不相邻的**token进行采样，通过map函数得到分组后的集合q_cls，k_cls，v_cls。
> 
> Thank you for your reply. So how does this reflect the allocation of tokens with the same color scheme to the same group mentioned in the paper？ I feel like the code is randomly grouped

Actually, the operation rearrange works on the tensor reshape and shuffle in our implementation. There is no random grouping. It is not easy to explain how this reflects because of the grouping operations on the high dimension of features. To simply understand our implementation, suppose we have a low-dimension tensor (2,4,4)

**Comment by LiyingCV** [comment]
> > **你好，具体实现意思是，我们对相同视角特征不相邻的**token进行采样，通过map函数得到分组后的集合q_cls，k_cls，v_cls。
> 
> Thank you for your reply. So how does this reflect the allocation of tokens with the same color scheme to the same group mentioned in the paper？ I feel like the code is randomly grouped

Actually, the operation rearrange works on the tensor reshape and shuffle in our implementation. **There is no random grouping**. It is not easy to explain how this reflects because of the grouping operations based on the high dimension of features. 
To understand our implementation, assume we have a low-dimension tensor (2,4,4), 2 is the batch size, the middle of 4 is the token num, and the last one is the dimension. 
`>>>a = torch.rand(2,4,4)`
`>>> a`
`tensor([[[0.2824, 0.9292, 0.7592, 0.8938],`
` [0.5135, 0.2825, 0.2301, 0.3340],`
`[0.7469, 0.4805, 0.6743, 0.1773],`
 `[0.8376, 0.8925, 0.7740, 0.7322]],`

 `[[0.5835, 0.1268, 0.3031, 0.8196],`
`[0.2566, 0.5805, 0.0033, 0.5275],`
 `[0.2391, 0.6764, 0.1403, 0.3989],`
 `[0.7516, 0.9074, 0.9079, 0.4663]]])`

Let us conduct `rearrange`, 
`>>>group_a = rearrange(a, 'b (n g) d-> b n g d', n=2,g=2)`
`>>>group_a`
`tensor([[[[0.2824, 0.9292, 0.7592, 0.8938],`
`[0.5135, 0.2825, 0.2301, 0.3340]],`

 `[[0.7469, 0.4805, 0.6743, 0.1773],`
`[0.8376, 0.8925, 0.7740, 0.7322]]],`

`[[[0.5835, 0.1268, 0.3031, 0.8196],`
`[0.2566, 0.5805, 0.0033, 0.5275]],`

`[[0.2391, 0.6764, 0.1403, 0.3989],`
`[0.7516, 0.9074, 0.9079, 0.4663]]]])`

Then we will get the result. By the way, the above operation differs from our implementation of the paper, but it can easily understand how to compute groups through tensor reshaping.
